package pl.kamilkoszarny.iotmanager.domain;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;
import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

/**
 * A Device.
 */
@Entity
@Table(name = "device")
@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
@Getter
@Setter
@ToString
public class Device implements Serializable {

    private static final long serialVersionUID = 1L;

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "sequenceGenerator")
    @SequenceGenerator(name = "sequenceGenerator")
    private Long id;

    @NotNull
    @Size(max = 50)
    @Column(name = "name", length = 50, nullable = false)
    private String name;

    @NotNull
    @Size(max = 80)
    @Column(name = "serial_no", length = 80, nullable = false)
    private String serialNo;

    @ManyToOne(optional = false)
    @NotNull
    @JsonIgnoreProperties(value = "models", allowSetters = true)
    private DeviceModel model;

    @ManyToOne(optional = false)
    @NotNull
    @JsonIgnoreProperties(value = "devices", allowSetters = true)
    private Site site;

    @OneToMany(mappedBy = "device", orphanRemoval = true)
    @Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
    private List<DeviceFault> faults = new ArrayList<>();

    public Device name(String name) {
        this.name = name;
        return this;
    }

    public Device serialNo(String serialNo) {
        this.serialNo = serialNo;
        return this;
    }

    public Device model(DeviceModel deviceModel) {
        this.model = deviceModel;
        return this;
    }

    public Device site(Site site) {
        this.site = site;
        return this;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (!(o instanceof Device)) {
            return false;
        }
        return id != null && id.equals(((Device) o).id);
    }

    //todo check if all hashCode methods needs to be generated by IDE rather than JHipster https://github.com/jhipster/generator-jhipster/issues/10097
    @Override
    public int hashCode() {
        return 31;
    }
}
